services:
  git-server:
    build: .
    container_name: git-server
    ports:
      - "2222:22"  # SSH
      - "8080:80"  # HTTP (Use a Reverse Proxy for HTTPS)
    volumes:
      - ./repos:/git-repos
      - ./keys/authorized_keys:/home/git/.ssh/authorized_keys
    restart: always