events { worker_connections 1024; }
http {
    server {
        listen 80;
        location ~ /(.+\.git)(/.*|$) {
            include /etc/nginx/fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /usr/libexec/git-core/git-http-backend;
            fastcgi_param GIT_HTTP_EXPORT_ALL "";
            fastcgi_param GIT_PROJECT_ROOT /git-repos;
            fastcgi_param HOME /home/git;
            fastcgi_param PATH_INFO $uri;
            fastcgi_pass unix:/run/fcgiwrap.socket;
        }
    }
}