import { useMutation, useQueryClient } from '@tanstack/react-query';
import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';

import { sshKeysApi } from '@/api/ssh-keys';
import { Alert } from '@/components/ui/Alert';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { FormGroup } from '@/components/ui/FormGroup';
import { Input } from '@/components/ui/Input';
import { queryKeys } from '@/lib/queryKeys';
import { addSshKeySchema, type AddSshKeyFormData } from '@/lib/schemas/ssh-keys';
import type { ApiError } from '@/types/api';

export function AddSshKeyForm() {
  const queryClient = useQueryClient();
  const { register, handleSubmit, formState, setError, reset } = useForm<AddSshKeyFormData>({
    resolver: zodResolver(addSshKeySchema),
  });

  const mutation = useMutation({
    mutationFn: (values: AddSshKeyFormData) => sshKeysApi.add(values),
    onSuccess: () => {
      reset();
      queryClient.invalidateQueries({ queryKey: queryKeys.sshKeys.list });
    },
    onError: (err: ApiError) => {
      if (err.status === 409) {
        setError('publicKey', { message: 'An SSH key with this fingerprint already exists.' });
      } else {
        setError('root', { message: err.message ?? 'Failed to add SSH key.' });
      }
    },
  });

  const onSubmit = (values: AddSshKeyFormData) => {
    mutation.mutate(values);
  };

  return (
    <section>
      <Card className="space-y-5 xl:sticky xl:top-24">
        <div className="space-y-1">
          <h2 className="text-2xl font-semibold text-gray-950 dark:text-white">
            Add a new SSH key
          </h2>
          <p className="text-sm text-gray-600 dark:text-gray-300">
            Paste the full public key exactly as generated by your SSH client.
          </p>
        </div>

        <form onSubmit={handleSubmit(onSubmit)} noValidate className="space-y-5">
          <FormGroup label="Title / label" required htmlFor="label">
            <Input
              id="label"
              type="text"
              placeholder="e.g. Work Laptop"
              error={formState.errors.label?.message}
              disabled={mutation.isPending}
              {...register('label')}
            />
          </FormGroup>

          <div className="space-y-2">
            <label
              htmlFor="publicKey"
              className="block text-sm font-medium text-gray-900 dark:text-gray-100"
            >
              Public key
            </label>
            <textarea
              id="publicKey"
              rows={7}
              placeholder="ssh-ed25519 AAAAC3... user@host"
              className="w-full rounded-lg border border-gray-300 bg-white px-4 py-3 font-mono text-sm text-gray-900 transition-colors duration-200 placeholder:text-gray-500 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-300 disabled:cursor-not-allowed disabled:opacity-50 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-100 dark:focus:ring-blue-500"
              disabled={mutation.isPending}
              {...register('publicKey')}
            />
            {formState.errors.publicKey ? (
              <p className="text-sm text-red-600 dark:text-red-400" role="alert">
                {formState.errors.publicKey.message}
              </p>
            ) : (
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Example: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI... user@machine
              </p>
            )}
          </div>

          {formState.errors.root ? (
            <Alert
              variant="error"
              message={formState.errors.root.message ?? 'Failed to add SSH key.'}
            />
          ) : null}

          <Button type="submit" className="w-full" loading={mutation.isPending}>
            Add key
          </Button>
        </form>
      </Card>
    </section>
  );
}
